[2025-09-16T15:12:12.913+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T15:12:12.944+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.extract_data_from_csv manual__2025-09-16T15:12:07.874328+00:00 [queued]>
[2025-09-16T15:12:12.953+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.extract_data_from_csv manual__2025-09-16T15:12:07.874328+00:00 [queued]>
[2025-09-16T15:12:12.954+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-16T15:12:12.970+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_from_csv> on 2025-09-16 15:12:07.874328+00:00
[2025-09-16T15:12:12.980+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-16T15:12:12.981+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2025-09-16T15:12:12.981+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nakhonpathom_waste_csv_etl_dag', 'extract_data_from_csv', 'manual__2025-09-16T15:12:07.874328+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/hazardous_waste_etl_dag.py', '--cfg-path', '/tmp/tmp6n3m8wgv']
[2025-09-16T15:12:12.983+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask extract_data_from_csv
[2025-09-16T15:12:13.032+0000] {task_command.py:426} INFO - Running <TaskInstance: nakhonpathom_waste_csv_etl_dag.extract_data_from_csv manual__2025-09-16T15:12:07.874328+00:00 [running]> on host aa7dbbbc41c4
[2025-09-16T15:12:13.125+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nakhonpathom_waste_csv_etl_dag' AIRFLOW_CTX_TASK_ID='extract_data_from_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T15:12:07.874328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T15:12:07.874328+00:00'
[2025-09-16T15:12:13.127+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T15:12:13.131+0000] {logging_mixin.py:188} INFO - Starting data extraction from CSV URL...
[2025-09-16T15:12:13.356+0000] {logging_mixin.py:188} INFO - Successfully read 347 rows from CSV.
[2025-09-16T15:12:13.390+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-16T15:12:13.391+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T15:12:13.400+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nakhonpathom_waste_csv_etl_dag, task_id=extract_data_from_csv, run_id=manual__2025-09-16T15:12:07.874328+00:00, execution_date=20250916T151207, start_date=20250916T151212, end_date=20250916T151213
[2025-09-16T15:12:13.437+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-16T15:12:13.463+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-16T15:12:13.468+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
